name: sentimento_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  provider: ^6.1.5+1
  fl_chart: ^1.1.1
  intl: ^0.20.2
  get_it: ^9.2.0
  logger: ^2.0.1
  go_router: ^17.0.1
  whatsapp_unilink: ^2.1.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.12.0
  json_path: ^0.9.0
  timeago: ^3.7.1
  from_css_color: ^2.0.0
  page_transition: ^2.2.1
  flutter_animate: ^4.5.2
  collection: ^1.17.2
  url_launcher: ^6.1.11
  shared_preferences: ^2.2.0
  rxdart: ^0.27.7
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  table_calendar: ^3.2.0
  image_picker: ^1.2.1
  image_cropper: 8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  import_sorter:
    git:
      url: https://github.com/Franklyn-R-Silva/import_sorter.git
      ref: feat/sort-pubspec


flutter:

  uses-material-design: true

  assets:
    - .env
