name: sentimento_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  app_settings: ^7.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  collection: ^1.17.2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_map: 7.0.2
  font_awesome_flutter: ^10.12.0
  from_css_color: ^2.0.0
  geolocator: 13.0.1
  get_it: ^9.2.0
  go_router: ^17.0.1
  image_cropper: 8.0.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_path: ^0.9.0
  latlong2: 0.9.1
  logger: ^2.0.1
  page_transition: ^2.2.1
  provider: ^6.1.5+1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  supabase_flutter: ^2.12.0
  table_calendar: ^3.2.0
  timeago: ^3.7.1
  timezone: ^0.10.0
  url_launcher: ^6.1.11
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  import_sorter:
    git:
      url: https://github.com/Franklyn-R-Silva/import_sorter.git
      ref: feat/sort-pubspec
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
